README.md
cli/main.go
sample/upload.json
synq/api.go
synq/video.go
synq/video_test.go

support /v1/video/upload API

---

circle.yml
cli/main.go
sample/aws_err.xml
synq/api.go
synq/api_test.go
synq/video.go
synq/video_test.go

refactor the code so that we can parse Synq and S3 return formats
redo UploadInfo struct so it's a map since the values are pretty much replicated for the multi-part form post
closes #4

support uploading a file through the API and cli

---

cli/main.go
synq/multipart_upload.go
synq/multipart_upload_test.go
synq/video.go

closes #12 build importer capability

Martin build importer capability2

---

synq/video.go

handle marshalling

---

.gitignore
cli/main.go
synq/api.go
synq/api_test.go
vendor/vendor.json

closes #32 
also fix up the available commands
closes #13

allow userdata to be passed in

---

sample/asset_created.json
sample/asset_list.json
sample/asset_uploaded.json
synq/api2.go
synq/api2_test.go
synq/asset.go
synq/asset_test.go
synq/base_api.go

implement asset calls

---

synq/api2.go
synq/asset.go
synq/video2.go
synq/video2_test.go
vendor/vendor.json

return a default message if there's no error message

update to convert id to uuid

---

sample/video2_update.json
synq/video2.go
synq/video2_test.go
test_server/synq.go

implement update, add tests

---

.circleci/config.yml
README.md
synq/api.go
synq/api2.go
synq/base_api.go
test_server/synq.go

fix it so that "New" still works

---

README.md
cli/main.go
sample/login.json
synq/api2.go
synq/api2_test.go
synq/video2.go
test_server/synq.go

This should be the preferred way to instantiate a new V2 API

implement "login"

---

synq/api2.go
synq/aws_upload.go
synq/aws_upload_test.go
test_server/synq.go

initial refactor of uploads

---

sample/v2/asset.json
sample/v2/upload.json
synq/api2.go
synq/api2_test.go
synq/asset.go
synq/video2.go

add new sample files for testing

add GetAsset method call

---

cli/main.go
helper/load.go
synq/api2.go
vendor/vendor.json

Also refactor to use the new helpers

add ability to just load the "raw" video bytes, without the objects

---

helper/load.go
synq/api2.go
vendor/github.com/buger/jsonparser/Dockerfile
vendor/github.com/buger/jsonparser/LICENSE
vendor/github.com/buger/jsonparser/Makefile
vendor/github.com/buger/jsonparser/README.md
vendor/github.com/buger/jsonparser/bytes.go
vendor/github.com/buger/jsonparser/bytes_safe.go
vendor/github.com/buger/jsonparser/bytes_unsafe.go
vendor/github.com/buger/jsonparser/escape.go
vendor/github.com/buger/jsonparser/parser.go

add better debug
change to https urls

add the jsonparser as part of the vendor

---

cli/main.go
cli/scripts/cmd.sh
cli/scripts/get_video.sh
cli/scripts/upload_for_asset.sh
cli/scripts/upload_for_video.sh
upload/aws.go
vendor/vendor.json

change signing to use v4 based signing, which can be used by Unicron
load credentials using the credentials.json file

upgrade to latest common

---

cli/main.go
helper/load.go
helper/load_test.go
synq/api2.go
synq/asset.go
synq/asset_test.go
synq/video2.go
synq/video2_test.go
upload/aws.go
upload/params.go
upload/params_test.go

by this and Unicorn.  This way we can consolidate on the same req object
remove legacy methods from V2

use new UploadRequest which is shared

---

helper/load_test.go
helper/setup.go
helper/setup_test.go
synq/api.go
synq/api2.go
synq/api2_test.go
synq/api_test.go
synq/asset_test.go
test_server/server.go

V1 stuff => version: "v1", route "v1"
V2 stuff => version: "v2", route "v1"
fixed tests in helper/load_test.go

Changed routes for V1 and V2

---

helper/load_test.go
synq/video2.go
synq/video2_test.go
test_server/README.md
upload/aws.go
upload/aws_test.go
upload/params.go

add README for test_server
for cleanup Thursdays 💃

improve test coverage

---

test_server/server.go
upload/aws_test.go

This is needed for hydra tests.

add to v2handler

---

helper/load.go
helper/load_test.go
vendor/vendor.json

change method signature since v2 doesn't have "query"

---

.circleci/config.yml
README.md

also fixed coveralls by deleting and re-creating the repo on coveralls.

upgrade config.yml

---

synq/asset.go

otherwise we'll end up with "0001" dates

omit if empty

---

metadata/synq_metadata.go

Adding VideoRights object to the asset object for Akka.

Adding rights object to assets

---

synq/api2.go
synq/video2.go
synq/video2_test.go

I need this for https://github.com/SYNQfm/incubus/issues/17

add function to get account details

---

sample/account.json
test_server/server.go

Needed for https://github.com/SYNQfm/incubus/issues/17

add mock result for get account query

---

synq/api2.go

update account struct

---

synq/api2.go

DO NOT MERGE UNTIL https://github.com/SYNQfm/akka/pull/323 IS MERGED

update account settings struct in accounts

---

metadata/synq_metadata.go

For mizuchi update in relation to https://github.com/SYNQfm/duwende/issues/298

add release year to metadata struct

---

sample/trailer_updated.json
sample/trailer_uploaded.json
test_server/server.go

I needed a different asset id/sample response for testing trailers in hydra.

add for trailer id

---

metadata/synq_metadata.go

revert previous changes with omitempty

---

metadata/synq_metadata.go

Update OtherInformation to use `map[string]interface{}` instead of LanguageList (`map[string]map[string]string`) so that it is more flexible with the data it accepts.

update other information type
